// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uodjtsxrvfysjdkephad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZGp0c3hydmZ5c2pka2VwaGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzE1MTAsImV4cCI6MjA1NjQ0NzUxMH0.lrTRMK9Ds3tPgRuZ4oW4ZedkCxDErZzZx67MJqZswtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);